# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: example-app
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: example-app
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        # you have to add your repo here:
        image: 0njev3grsqmz0zl8/myapp:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: example-app
spec:
  selector:
    app: myapp
  ports:
    - port: 8080
      targetPort: 80
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  namespace: example-app
  # https://kubernetes.github.io/ingress-nginx/examples/rewrite/
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: myapp
                port:
                  number: 8080
